easy_admin:
     entities:
         # List the entity class name you want to manage
         - App\Entity\RailScale
         - App\Entity\RailConstructor
         - App\Entity\StraightRail
         - App\Entity\ElectricRail
         - App\Entity\SwitchRail
         - App\Entity\CurvedRail
